USE [master]
GO

/****** Object:  Database [SQLProgramiranjeProjekat]    Script Date: 1/23/2021 12:49:01 AM ******/
CREATE DATABASE [SQLProgramiranjeProjekat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SQLProgramiranjeProjekat', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SQLProgramiranjeProjekat.mdf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 15%)
 LOG ON 
( NAME = N'SQLProgramiranjeProjekat_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SQLProgramiranjeProjekat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SQLProgramiranjeProjekat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET ARITHABORT OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET RECOVERY FULL 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET  MULTI_USER 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SQLProgramiranjeProjekat] SET  READ_WRITE 
GO


